### ISSUE TITLE
Missing property after upgrade to 2sxc 16.03.00

### ISSUE THREAD

**Issue by skarpik** [2sic/2sxc#3162]
### I'm submitting a

[x] bug report => search github for a similar issue before submitting

### ...about

[x] Razor templating

### Current Behavior / Expected Behavior

Over 5 years ago, I modified the Blue Imp photo gallery (v3.2) to add another view. I have encountered no problems with multiple 2sxc upgrades including v16.02.00.  However, when I upgraded to 2sxc v16.03.00, I got the following error message:

'ToSic.Sxc.Data.IMetadata' does not contain a definition for 'EntityId' and no extension method 'EntityId' accepting a first argument of type 'ToSic.Sxc.Data.IMetadata'

with reference to the line of code:

<ul class="sc-menu" data-toolbar='{ "action": "metadata", "entityId": @pic.Metadata.EntityId, "contentType":"ImageMetadata", "metadata":{"key":"file:@pic.FileId"}}'></ul>

Here is the full error message:

Error: System.Web.HttpCompileException (0x80004005): d:\Websites\rcrm-2sxc16-03-00\Website\Portals\0\2sxc\blueimp Gallery\_Gallery Tiles with Text Overlay.cshtml(189): error CS1061: 'ToSic.Sxc.Data.IMetadata' does not contain a definition for 'EntityId' and no extension method 'EntityId' accepting a first argument of type 'ToSic.Sxc.Data.IMetadata' could be found (are you missing a using directive or an assembly reference?) at System.Web.Compilation.AssemblyBuilder.Compile() at System.Web.Compilation.BuildProvidersCompiler.PerformBuild() at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound) at System.Web.Compilation.BuildManager.GetCompiledType(VirtualPath virtualPath) at ToSic.Sxc.Engines.RazorEngine.CreateWebPageInstance() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Engines\Razor\RazorEngine.cs:line 133 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at ToSic.Sxc.Engines.RazorEngine.CreateWebPageInstance() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Engines\Razor\RazorEngine.cs:line 150 at ToSic.Sxc.Engines.RazorEngine.InitWebpage() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Engines\Razor\RazorEngine.cs:line 177 at ToSic.Sxc.Engines.RazorEngine.Init() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Engines\Razor\RazorEngine.cs:line 74 at ToSic.Lib.Logging.ILog_Actions.Do(ILog log, String parameters, Action action, Boolean timer, Boolean enabled, String message, String cPath, String cName, Int32 cLine) in C:\Projects\2sxc\eav-server\ToSic.Lib.Core\Logging\Log\ILog_Actions.cs:line 64 at ToSic.Sxc.Engines.EngineBase.Init(IBlock block) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Engines\EngineBase.cs:line 79 at ToSic.Sxc.Blocks.BlockBuilder.GetEngine() in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Blocks\BlockBuilder_Render.cs:line 270 at ToSic.Sxc.Dnn.Web.DnnClientResources.NeedsPre1025Behavior() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\Web\DnnClientResources.cs:line 90 at ToSic.Sxc.Dnn.View.<>c__DisplayClass14_0.<Page_Load>b__3() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\View.ascx.cs:line 93 at ToSic.Sxc.Dnn.View.TryCatchAndLogToDnn[TResult](Func`1 action) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\View.ascx.Errors.cs:line 22 - CONTEXT: Page: 43; Module: 866

### Instructions to Reproduce the Problem

Install Blue Imp photo gallery v3.2 with 2sxc prior to v16.03.00. Then upgrade to 2sxc v16.03.00.

### Your environment

* **2sxc version(s):** 16.03.0
* **Browser:** all 
* **DNN:** v9.12.0
* **Hosting platform:** IIS 
* **Language:** any/all

**Comment by iJungleboy** [comment]
@skarpik Thanks for spotting this.
I'll see what we can do to fix this in 2-3 days.

**Comment by skarpik** [comment]
@jeremy-farrance found a workaround for the problem. If I replace @pic.Metadata.EntityId with @pic.Metadata.Id, the code appears to work as expected. The app shows the content now. I haven't verified that I can add/delete/edit images. Thanks for looking into this.  Working with such a collection of apps of all versions as is 2sxc, there have to be a few oddballs like this one that trip you up. Thanks for looking into this.

**Comment by iJungleboy** [comment]
Already added a fix, but the future should be to use `Metadata.Id` instead, so if `Metadata.EntityId` is used, it will work, but show a warning to the super-user about obsolete code being used. 

Will be in 16.05, in 2-3 days.
